### ISSUE TITLE
Append UK to Weather URL

### ISSUE THREAD

**Issue by totalretribution** [f0rkz/Bootstrap-Nest-Administration-Tool#24]
Hi, I kept getting an null outside_temp error until I appended ",GB" to the weather url i.e https://home.nest.com/api/0.1/weather/forecast/GL526BD,GB

I came across this issue and a fix on nest-api here https://github.com/gboudreau/nest-api/issues/50

**Comment by pfidr34** [comment]
Feel free to mark this resolved as a code change has been merged.
