### ISSUE TITLE
Graph Displays in UTC despite proper timezone

### ISSUE THREAD

**Issue by SxthGear** [f0rkz/Bootstrap-Nest-Administration-Tool#26]
Graphs are currently rendering in UTC despite a verified timezone configured in nest.conf.php. Tried with two different time zones (America/Chicago and America/Detroit), which should be -5:00 from UTC.

**Comment by pfidr34** [comment]
Not sure there is an issue here.

My normal offset is -5 for CST. Time displays correctly.
I then set my offset to -10 to test. Time rolled back 5 hours as expected.

To test I was using: 
UPDATE `users` SET `timestamp_offset` = '-10' WHERE `users`.`user_id` = 1;
UPDATE `users` SET `timestamp_offset` = '-5' WHERE `users`.`user_id` = 1;

Be sure to ctrl+F5 on your webpage graph to see the update.

Images of time change: [http://imgur.com/a/JlXwD](url)

**Comment by SxthGear** [comment]
Forced the change via mysql using the same test, and it has now updated to the correct time offset. Not sure why it wasn't updating before. Thanks!
